<?php

return [
    'header' => [
        'type' => 'pro',
        'icon' => 'fas fa-theater-masks',
        'color' => '#61B123',
        'has_statistics' => true,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_image_extensions' => ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'avif'],
        'category' => 'advanced',
    ],
    'applemusic' => [
        'type' => 'pro',
        'icon' => 'fab fa-apple',
        'color' => '#FA2D48',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['music.apple.com'],
        'category' => 'embeds',
    ],
    'mixcloud' => [
        'type' => 'default',
        'icon' => 'fab fa-mixer',
        'color' => '#4e00ff',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['www.mixcloud.com'],
        'category' => 'embeds',
    ],
    'kick' => [
        'type' => 'default',
        'icon' => 'fab fa-kickstarter',
        'color' => '#5eff1b',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['kick.com'],
        'category' => 'embeds',
    ],
    'twitter_profile' => [
        'type' => 'pro',
        'icon' => 'fab fa-x-twitter',
        'color' => '#1DA1F2',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['twitter.com', 'x.com'],
        'category' => 'embeds',
    ],
    'twitter_tweet' => [
        'type' => 'pro',
        'icon' => 'fab fa-x-twitter',
        'color' => '#1DA1F2',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['twitter.com', 'x.com'],
        'category' => 'embeds',
    ],
    'twitter_video' => [
        'type' => 'pro',
        'icon' => 'fab fa-x-twitter',
        'color' => '#1DA1F2',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['twitter.com', 'x.com'],
        'category' => 'embeds',
    ],
    'pinterest_profile' => [
        'type' => 'pro',
        'icon' => 'fab fa-pinterest',
        'color' => '#c8232c',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['pinterest.com', 'www.pinterest.com'],
        'category' => 'embeds',
    ],
    'instagram_media' => [
        'type' => 'pro',
        'icon' => 'fab fa-instagram',
        'color' => '#F56040',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['www.instagram.com'],
        'category' => 'embeds',
    ],
    'snapchat' => [
        'type' => 'pro',
        'icon' => 'fab fa-snapchat',
        'color' => '#FFFC00',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['www.snapchat.com', 'snapchat.com'],
        'category' => 'embeds',
    ],
    'custom_html' => [
        'type' => 'pro',
        'icon' => 'fas fa-code',
        'color' => '#02234c',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'max_length' => 16384,
        'category' => 'advanced',
    ],
    'image_grid' => [
        'type' => 'pro',
        'icon' => 'fas fa-images',
        'color' => '#183153',
        'has_statistics' => true,
        'themable' => false,
        'display_dynamic_name' => 'name',
        'whitelisted_image_extensions' => ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'avif'],
        'category' => 'standard',
    ],
    'divider' => [
        'type' => 'pro',
        'icon' => 'fas fa-grip-lines',
        'color' => '#30a85a',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'category' => 'standard',
    ],
    'list' => [
        'type' => 'pro',
        'icon' => 'fas fa-list',
        'color' => '#2b385e',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => 'text',
        'category' => 'standard',
    ],
    'alert' => [
        'type' => 'pro',
        'icon' => 'fas fa-bell',
        'color' => '#1500ff',
        'has_statistics' => true,
        'themable' => false,
        'display_dynamic_name' => 'text',
        'category' => 'advanced',
    ],
    'tiktok_profile' => [
        'type' => 'pro',
        'icon' => 'fab fa-tiktok',
        'color' => '#FD3E3E',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['www.tiktok.com'],
        'category' => 'embeds',
    ],
];
