version: '3.8'

services:
  app-nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - nginx-cache:/var/cache/nginx
      - ssl-certs:/etc/letsencrypt
    depends_on:
      - php
    networks:
      app-network:
        ipv4_address: 172.20.0.5
    restart: unless-stopped
    environment:
      - NGINX_HOST=${DOMAIN_NAME:-localhost}

  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html
      - php-cache:/tmp
    depends_on:
      - mysql
    networks:
      app-network:
        ipv4_address: 172.20.0.8
    restart: unless-stopped
    environment:
      - DATABASE_SERVER=mysql
      - DATABASE_USERNAME=seegap_prod_user_2025
      - DATABASE_PASSWORD=SeeGapProd2025MySQLSecure
      - DATABASE_NAME=seegap_application_db
      - SITE_URL=http://localhost/
      - PHP_OPCACHE_ENABLE=1
      - PHP_APCU_ENABLE=1

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=seegap_application_db
      - MYSQL_USER=seegap_prod_user_2025
      - MYSQL_PASSWORD=SeeGapProd2025MySQLSecure
      - MYSQL_ROOT_PASSWORD=Root#MySQL!SuperSecure@GCP
    networks:
      app-network:
        ipv4_address: 172.20.0.10
    restart: unless-stopped
    command: --innodb-buffer-pool-size=128M --max-connections=100

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    networks:
      app-network:
        ipv4_address: 172.20.0.12
    restart: unless-stopped
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
  nginx-cache:
    driver: local
  php-cache:
    driver: local
  ssl-certs:
    driver: local

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
