<?php
/*
 * Copyright (c) 2025 SeeGap Ltd. (https://seegap.com/)
 *
 * This software is licensed to SeeGap Ltd..
 * Licensed software, not for unauthorized distribution or use.
 */

namespace SeeGap\Controllers;

use SeeGap\Alerts;
use SeeGap\Response;

defined('SEEGAP') || die();

class ProductAjax extends Controller {

    public function index() {
        die();
    }

    public function duplicate() {
        \SeeGap\Authentication::guard();

        /* Team checks */
        if(\SeeGap\Teams::is_delegated() && !\SeeGap\Teams::has_access('create.products')) {
            Response::json(l('global.info_message.team_no_access'), 'error');
        }

        if(empty($_POST)) {
            Response::json(l('global.error_message.empty_request'), 'error');
        }

        $product_id = (int) $_POST['product_id'];

        if(!\SeeGap\Csrf::check()) {
            Response::json(l('global.error_message.invalid_csrf_token'), 'error');
        }

        /* Get the source product */
        $product = (new \SeeGap\Models\Product())->get_product_by_id($product_id, $this->user->user_id);
        if(!$product) {
            Response::json(l('global.error_message.not_found'), 'error');
        }

        /* Check for the plan limit */
        $total_rows = database()->query("SELECT COUNT(*) AS `total` FROM `products` WHERE `user_id` = {$this->user->user_id}")->fetch_object()->total ?? 0;
        if(($this->user->plan_settings->products_limit ?? -1) != -1 && $total_rows >= ($this->user->plan_settings->products_limit ?? 0)) {
            Response::json(l('global.info_message.plan_feature_limit'), 'error');
        }

        /* Prepare the data */
        $product_data = [
            'user_id' => $this->user->user_id,
            'project_id' => $product->project_id,
            'brand_name' => $product->brand_name,
            'product_name' => $product->product_name . ' (Copy)',
            'product_description' => $product->product_description,
            'category' => $product->category,
            'subcategory' => $product->subcategory,
            'manufacturer' => $product->manufacturer,
            'country_of_origin' => $product->country_of_origin,
            'net_weight' => $product->net_weight,
            'dimensions' => $product->dimensions,
            'ingredients' => $product->ingredients,
            'nutritional_info' => $product->nutritional_info,
            'allergen_info' => $product->allergen_info,
            'certifications' => $product->certifications,
            'packaging_info' => $product->packaging_info,
            'storage_instructions' => $product->storage_instructions,
            'usage_instructions' => $product->usage_instructions,
            'target_url' => $product->target_url,
            'product_images' => $product->product_images,
            'settings' => $product->settings,
            'is_enabled' => $product->is_enabled,
            'gtin' => '', // Will be generated by create_product()
            'gs1_link_id' => null // New product needs its own GS1 link
        ];

        /* Create the new product */
        $product_model = new \SeeGap\Models\Product();
        $new_product_id = $product_model->create_product($product_data);

        if(!$new_product_id) {
            Response::json(l('products.error_message.creation_failed'), 'error');
        }

        Response::json(sprintf(l('global.success_message.create1'), '<strong>' . $product_data['product_name'] . '</strong>'), 'success', [
            'url' => url('product-update/' . $new_product_id)
        ]);
    }

    public function is_enabled_toggle() {
        \SeeGap\Authentication::guard();

        /* Team checks */
        if(\SeeGap\Teams::is_delegated() && !\SeeGap\Teams::has_access('update.products')) {
            Response::json(l('global.info_message.team_no_access'), 'error');
        }

        if(empty($_POST)) {
            Response::json(l('global.error_message.empty_request'), 'error');
        }

        $product_id = (int) $_POST['product_id'];

        if(!\SeeGap\Csrf::check('token', 'url')) {
            Response::json(l('global.error_message.invalid_csrf_token'), 'error');
        }

        /* Get the current product */
        if(!$product = db()->where('product_id', $product_id)->where('user_id', $this->user->user_id)->getOne('products', ['product_id', 'is_enabled'])) {
            Response::json(l('global.error_message.not_found'), 'error');
        }

        $new_is_enabled = (int) !$product->is_enabled;

        db()->where('product_id', $product_id)->update('products', [
            'is_enabled' => $new_is_enabled,
            'last_datetime' => \SeeGap\Date::$date
        ]);

        Response::json(l('global.success_message.update2'), 'success');
    }
}
