<?php
/*
 * Copyright (c) 2025 SeeGap Ltd. (https://seegap.com/)
 *
 * This software is licensed to SeeGap Ltd..
 * Licensed software, not for unauthorized distribution or use.
 */

namespace SeeGap\Controllers;

use SeeGap\Alerts;
use SeeGap\Response;

defined('SEEGAP') || die();

class ProductAjax extends Controller {

    public function index() {
        \SeeGap\Authentication::guard();

        if(empty($_POST)) {
            Response::json(l('global.error_message.empty_request'), 'error');
        }

        $type = input_clean($_POST['type'] ?? '');

        switch($type) {
            case 'get_existing_content':
                $this->get_existing_content();
                break;
            
            case 'duplicate':
                $this->duplicate();
                break;
                
            case 'is_enabled_toggle':
                $this->is_enabled_toggle();
                break;
                
            default:
                Response::json(l('global.error_message.invalid_request'), 'error');
                break;
        }
    }

    public function duplicate() {
        \SeeGap\Authentication::guard();

        /* Team checks */
        if(\SeeGap\Teams::is_delegated() && !\SeeGap\Teams::has_access('create.products')) {
            Response::json(l('global.info_message.team_no_access'), 'error');
        }

        if(empty($_POST)) {
            Response::json(l('global.error_message.empty_request'), 'error');
        }

        $product_id = (int) $_POST['product_id'];

        if(!\SeeGap\Csrf::check()) {
            Response::json(l('global.error_message.invalid_csrf_token'), 'error');
        }

        /* Get the source product */
        $product = (new \SeeGap\Models\Product())->get_product_by_id($product_id, $this->user->user_id);
        if(!$product) {
            Response::json(l('global.error_message.not_found'), 'error');
        }

        /* Check for the plan limit */
        $total_rows = database()->query("SELECT COUNT(*) AS `total` FROM `products` WHERE `user_id` = {$this->user->user_id}")->fetch_object()->total ?? 0;
        if(($this->user->plan_settings->products_limit ?? -1) != -1 && $total_rows >= ($this->user->plan_settings->products_limit ?? 0)) {
            Response::json(l('global.info_message.plan_feature_limit'), 'error');
        }

        /* Prepare the data */
        $product_data = [
            'user_id' => $this->user->user_id,
            'project_id' => $product->project_id,
            'brand_name' => $product->brand_name,
            'product_name' => $product->product_name . ' (Copy)',
            'product_description' => $product->product_description,
            'category' => $product->category,
            'subcategory' => $product->subcategory,
            'manufacturer' => $product->manufacturer,
            'country_of_origin' => $product->country_of_origin,
            'net_weight' => $product->net_weight,
            'dimensions' => $product->dimensions,
            'ingredients' => $product->ingredients,
            'nutritional_info' => $product->nutritional_info,
            'allergen_info' => $product->allergen_info,
            'certifications' => $product->certifications,
            'packaging_info' => $product->packaging_info,
            'storage_instructions' => $product->storage_instructions,
            'usage_instructions' => $product->usage_instructions,
            'target_url' => $product->target_url,
            'product_images' => $product->product_images,
            'settings' => $product->settings,
            'is_enabled' => $product->is_enabled,
            'gtin' => '', // Will be generated by create_product()
            'gs1_link_id' => null // New product needs its own GS1 link
        ];

        /* Create the new product */
        $product_model = new \SeeGap\Models\Product();
        $new_product_id = $product_model->create_product($product_data);

        if(!$new_product_id) {
            Response::json(l('products.error_message.creation_failed'), 'error');
        }

        Response::json(sprintf(l('global.success_message.create1'), '<strong>' . $product_data['product_name'] . '</strong>'), 'success', [
            'url' => url('product-update/' . $new_product_id)
        ]);
    }

    public function is_enabled_toggle() {
        \SeeGap\Authentication::guard();

        /* Team checks */
        if(\SeeGap\Teams::is_delegated() && !\SeeGap\Teams::has_access('update.products')) {
            Response::json(l('global.info_message.team_no_access'), 'error');
        }

        if(empty($_POST)) {
            Response::json(l('global.error_message.empty_request'), 'error');
        }

        $product_id = (int) $_POST['product_id'];

        if(!\SeeGap\Csrf::check('token', 'url')) {
            Response::json(l('global.error_message.invalid_csrf_token'), 'error');
        }

        /* Get the current product */
        if(!$product = db()->where('product_id', $product_id)->where('user_id', $this->user->user_id)->getOne('products', ['product_id', 'is_enabled'])) {
            Response::json(l('global.error_message.not_found'), 'error');
        }

        $new_is_enabled = (int) !$product->is_enabled;

        db()->where('product_id', $product_id)->update('products', [
            'is_enabled' => $new_is_enabled,
            'last_datetime' => \SeeGap\Date::$date
        ]);

        Response::json(l('global.success_message.update2'), 'success');
    }

    public function get_existing_content() {
        \SeeGap\Authentication::guard();

        if(empty($_POST)) {
            Response::json(l('global.error_message.empty_request'), 'error');
        }

        if(!\SeeGap\Csrf::check()) {
            Response::json(l('global.error_message.invalid_csrf_token'), 'error');
        }

        $content_type = input_clean($_POST['content_type'] ?? '');
        $data = [];

        // Debug logging
        error_log("ProductAjax get_existing_content called with type: " . $content_type . " for user: " . $this->user->user_id);

        try {
            switch($content_type) {
                case 'microsite':
                    $results = database()->query("SELECT `link_id`, `url`, `settings` FROM `links` WHERE `user_id` = {$this->user->user_id} AND `type` = 'microsite' ORDER BY `datetime` DESC");
                    
                    while($result = $results->fetch_object()) {
                        $settings = json_decode($result->settings ?? '{}');
                        $name = $settings->title ?? $result->url;
                        $data[] = [
                            'id' => $result->link_id,
                            'name' => $name . ' (' . $result->url . ')'
                        ];
                    }
                    break;

                case 'link':
                    $results = database()->query("SELECT `link_id`, `url`, `location_url` FROM `links` WHERE `user_id` = {$this->user->user_id} AND `type` = 'link' ORDER BY `datetime` DESC");
                    
                    while($result = $results->fetch_object()) {
                        $data[] = [
                            'id' => $result->link_id,
                            'name' => $result->url . ' → ' . $result->location_url
                        ];
                    }
                    break;

                case 'file':
                    $results = database()->query("SELECT `link_id`, `url`, `settings` FROM `links` WHERE `user_id` = {$this->user->user_id} AND `type` = 'file' ORDER BY `datetime` DESC");
                    
                    while($result = $results->fetch_object()) {
                        $settings = json_decode($result->settings ?? '{}');
                        $filename = $settings->file_name ?? 'File';
                        $data[] = [
                            'id' => $result->link_id,
                            'name' => $filename . ' (' . $result->url . ')'
                        ];
                    }
                    break;

                case 'event':
                    $results = database()->query("SELECT `link_id`, `url`, `settings` FROM `links` WHERE `user_id` = {$this->user->user_id} AND `type` = 'event' ORDER BY `datetime` DESC");
                    
                    while($result = $results->fetch_object()) {
                        $settings = json_decode($result->settings ?? '{}');
                        $event_name = $settings->name ?? 'Event';
                        $data[] = [
                            'id' => $result->link_id,
                            'name' => $event_name . ' (' . $result->url . ')'
                        ];
                    }
                    break;

                case 'static':
                    // Get static pages or splash pages
                    $results = database()->query("SELECT `splash_page_id`, `name`, `url` FROM `splash_pages` WHERE `user_id` = {$this->user->user_id} ORDER BY `datetime` DESC");
                    
                    while($result = $results->fetch_object()) {
                        $data[] = [
                            'id' => 'splash_' . $result->splash_page_id,
                            'name' => $result->name . ' (' . $result->url . ')'
                        ];
                    }
                    break;

                default:
                    error_log("ProductAjax get_existing_content: Invalid content type: " . $content_type);
                    Response::json('Invalid content type', 'error');
                    break;
            }

            // Debug logging
            error_log("ProductAjax get_existing_content found " . count($data) . " items for type: " . $content_type);

            Response::json('', 'success', ['data' => $data]);
            
        } catch (Exception $e) {
            // Log the error for debugging
            error_log('ProductAjax get_existing_content error: ' . $e->getMessage());
            Response::json('Error loading content: ' . $e->getMessage(), 'error');
        }
    }
}
