<?php
/*
 * Copyright (c) 2025 SeeGap Ltd. (https://seegap.com/)
 *
 * This software is licensed to SeeGap Ltd..
 * Licensed software, not for unauthorized distribution or use.
 *
 */

defined('SEEGAP') || die();

$payment_blocks = \SeeGap\Plugin::is_active('payment-blocks') && file_exists(\SeeGap\Plugin::get('payment-blocks')->path . 'payment_blocks.php') ? include \SeeGap\Plugin::get('payment-blocks')->path . 'payment_blocks.php' : [];

$default_blocks = [
    'link' => [
        'type' => 'default',
        'icon' => 'fas fa-fw fa-link',
        'color' => '#004ecc',
        'has_statistics' => true,
        'themable' => true,
        'display_dynamic_name' => 'name',
        'whitelisted_thumbnail_image_extensions' => ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'avif'],
        'category' => 'standard',
    ],
    'heading' => [
        'type' => 'default',
        'icon' => 'fas fa-fw fa-heading',
        'color' => '#000000',
        'has_statistics' => false,
        'themable' => true,
        'display_dynamic_name' => 'text',
        'category' => 'standard',
    ],
    'paragraph' => [
        'type' => 'default',
        'icon' => 'fas fa-fw fa-paragraph',
        'color' => '#494949',
        'has_statistics' => false,
        'themable' => true,
        'display_dynamic_name' => 'text',
        'category' => 'standard',
    ],
    'avatar' => [
        'type' => 'default',
        'icon' => 'fas fa-fw fa-user',
        'color' => '#8b2abf',
        'has_statistics' => true,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_image_extensions' => ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'avif'],
        'category' => 'standard',
    ],
    'image' => [
        'type' => 'default',
        'icon' => 'fas fa-fw fa-image',
        'color' => '#0682FF',
        'has_statistics' => true,
        'themable' => false,
        'display_dynamic_name' => 'image_alt',
        'whitelisted_image_extensions' => ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'avif'],
        'category' => 'standard',
    ],
    'socials' => [
        'type' => 'default',
        'icon' => 'fas fa-fw fa-users',
        'color' => '#63d2ff',
        'has_statistics' => false,
        'themable' => true,
        'display_dynamic_name' => false,
        'category' => 'standard',
    ],
    'email_collector' => [
        'type' => 'default',
        'icon' => 'fas fa-envelope',
        'color' => '#c91685',
        'has_statistics' => false,
        'themable' => true,
        'display_dynamic_name' => 'name',
        'whitelisted_thumbnail_image_extensions' => ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'avif'],
        'category' => 'advanced',
    ],
    'threads' => [
        'type' => 'default',
        'icon' => 'fab fa-threads',
        'color' => '#f54640',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['threads.net', 'www.threads.net'],
        'category' => 'embeds',
    ],
    'soundcloud' => [
        'type' => 'default',
        'icon' => 'fab fa-soundcloud',
        'color' => '#ff8800',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['soundcloud.com'],
        'category' => 'embeds',
    ],
    'spotify' => [
        'type' => 'default',
        'icon' => 'fab fa-spotify',
        'color' => '#1db954',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['open.spotify.com'],
        'category' => 'embeds',
    ],
    'youtube' => [
        'type' => 'default',
        'icon' => 'fab fa-youtube',
        'color' => '#ff0000',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['www.youtube.com', 'youtu.be'],
        'category' => 'embeds',
    ],
    'twitch' => [
        'type' => 'default',
        'icon' => 'fab fa-twitch',
        'color' => '#6441a5',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['www.twitch.tv'],
        'category' => 'embeds',
    ],
    'vimeo' => [
        'type' => 'default',
        'icon' => 'fab fa-vimeo',
        'color' => '#1ab7ea',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['vimeo.com'],
        'category' => 'embeds',
    ],
    'tiktok_video' => [
        'type' => 'default',
        'icon' => 'fab fa-tiktok',
        'color' => '#FD3E3E',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['www.tiktok.com'],
        'category' => 'embeds',
    ],
    'paypal' => [
        'type' => 'default',
        'icon' => 'fab fa-fw fa-paypal',
        'color' => '#00457C',
        'has_statistics' => true,
        'themable' => true,
        'display_dynamic_name' => 'name',
        'whitelisted_thumbnail_image_extensions' => ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'avif'],
        'category' => 'payments',
    ],
    'phone_collector' => [
        'type' => 'default',
        'icon' => 'fas fa-phone-square-alt',
        'color' => '#39c640',
        'has_statistics' => false,
        'themable' => true,
        'display_dynamic_name' => 'name',
        'whitelisted_thumbnail_image_extensions' => ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'avif'],
        'category' => 'advanced',
    ],
    'contact_collector' => [
        'type' => 'default',
        'icon' => 'fas fa-address-book',
        'color' => '#7136c0',
        'has_statistics' => false,
        'themable' => true,
        'display_dynamic_name' => 'name',
        'whitelisted_thumbnail_image_extensions' => ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'avif'],
        'category' => 'advanced',
    ],
    'feedback_collector' => [
        'type' => 'default',
        'icon' => 'fas fa-address-book',
        'color' => '#7136c0',
        'has_statistics' => false,
        'themable' => true,
        'display_dynamic_name' => 'name',
        'whitelisted_thumbnail_image_extensions' => ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'avif'],
        'category' => 'advanced',
    ],
    'image_slider' => [
        'type' => 'default',
        'icon' => 'fas fa-clone',
        'color' => '#290b5b',
        'has_statistics' => true,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_image_extensions' => ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'avif'],
        'category' => 'standard',
    ],
    'image_grid' => [
        'type' => 'default',
        'icon' => 'fas fa-th',
        'color' => '#0682FF',
        'has_statistics' => true,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_image_extensions' => ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'avif'],
        'category' => 'standard',
    ],
    'big_link' => [
        'type' => 'default',
        'icon' => 'fas fa-fw fa-external-link-alt',
        'color' => '#cc0084',
        'has_statistics' => true,
        'themable' => true,
        'display_dynamic_name' => 'name',
        'whitelisted_thumbnail_image_extensions' => ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'avif'],
        'category' => 'standard',
    ],
    'faq' => [
        'type' => 'default',
        'icon' => 'fas fa-feather',
        'color' => '#da2a73',
        'has_statistics' => false,
        'themable' => true,
        'display_dynamic_name' => false,
        'category' => 'advanced',
    ],
    'facebook' => [
        'type' => 'default',
        'icon' => 'fab fa-facebook',
        'color' => '#4267B2',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['www.facebook.com', 'fb.watch'],
        'category' => 'embeds',
    ],
    'iframe' => [
        'type' => 'default',
        'icon' => 'fas fa-crop-alt',
        'color' => '#366bff',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'category' => 'standard',
    ],
    'file' => [
        'type' => 'default',
        'icon' => 'fas fa-file',
        'color' => '#8c8c8c',
        'has_statistics' => true,
        'themable' => true,
        'display_dynamic_name' => 'name',
        'whitelisted_file_extensions' => ['pdf', 'zip', 'rar', 'doc', 'docx'],
        'whitelisted_thumbnail_image_extensions' => ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'avif'],
        'category' => 'standard',
    ],
    'countdown' => [
        'type' => 'default',
        'icon' => 'fas fa-clock',
        'color' => '#2b2b2b',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'category' => 'advanced',
    ],
    'cta' => [
        'type' => 'default',
        'icon' => 'fas fa-comments',
        'color' => '#3100d6',
        'has_statistics' => true,
        'themable' => true,
        'display_dynamic_name' => 'name',
        'whitelisted_thumbnail_image_extensions' => ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'avif'],
        'category' => 'standard',
    ],
    'external_item' => [
        'type' => 'default',
        'icon' => 'fas fa-money-bill-wave',
        'color' => '#00ce18',
        'has_statistics' => true,
        'themable' => false,
        'display_dynamic_name' => 'name',
        'whitelisted_thumbnail_image_extensions' => ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'avif'],
        'category' => 'advanced',
    ],
    'share' => [
        'type' => 'default',
        'icon' => 'fas fa-share-square',
        'color' => '#00d3ac',
        'has_statistics' => true,
        'themable' => true,
        'display_dynamic_name' => 'name',
        'whitelisted_thumbnail_image_extensions' => ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'avif'],
        'category' => 'advanced',
    ],
    'coupon' => [
        'type' => 'default',
        'icon' => 'fas fa-tags',
        'color' => '#6fd9f0',
        'has_statistics' => true,
        'themable' => true,
        'display_dynamic_name' => 'name',
        'whitelisted_thumbnail_image_extensions' => ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'avif'],
        'category' => 'advanced',
    ],
    'youtube_feed' => [
        'type' => 'default',
        'icon' => 'fab fa-youtube',
        'color' => '#282828',
        'has_statistics' => false,
        'themable' => true,
        'display_dynamic_name' => false,
        'category' => 'advanced',
    ],
    'timeline' => [
        'type' => 'default',
        'icon' => 'fas fa-ellipsis-v',
        'color' => '#3c526d',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'category' => 'advanced',
    ],
    'review' => [
        'type' => 'default',
        'icon' => 'fas fa-star',
        'color' => '#ffe100',
        'has_statistics' => false,
        'themable' => true,
        'display_dynamic_name' => 'title',
        'whitelisted_image_extensions' => ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'avif'],
        'category' => 'advanced',
    ],
    'pdf_document' => [
        'type' => 'default',
        'icon' => 'fas fa-file-pdf',
        'color' => '#AA1501',
        'has_statistics' => true,
        'themable' => true,
        'display_dynamic_name' => 'name',
        'whitelisted_file_extensions' => ['pdf'],
        'whitelisted_thumbnail_image_extensions' => ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'avif'],
        'category' => 'embeds',
    ],
    'markdown' => [
        'type' => 'default',
        'icon' => 'fas fa-sticky-note',
        'color' => '#ff8300',
        'has_statistics' => false,
        'themable' => true,
        'display_dynamic_name' => false,
        'category' => 'advanced',
    ],
    'typeform' => [
        'type' => 'default',
        'icon' => 'fas fa-keyboard',
        'color' => '#000000',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'category' => 'embeds',
    ],
    'calendly' => [
        'type' => 'default',
        'icon' => 'fas fa-calendar',
        'color' => '#2d69f6',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'category' => 'embeds',
    ],
    'header' => [
        'type' => 'default',
        'icon' => 'fas fa-theater-masks',
        'color' => '#61B123',
        'has_statistics' => true,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_image_extensions' => ['jpg', 'jpeg', 'png', 'svg', 'gif', 'webp', 'avif'],
        'category' => 'advanced',
    ],
    'twitter_profile' => [
        'type' => 'default',
        'icon' => 'fab fa-x-twitter',
        'color' => '#1DA1F2',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['twitter.com', 'x.com'],
        'category' => 'embeds',
    ],
    'twitter_tweet' => [
        'type' => 'default',
        'icon' => 'fab fa-x-twitter',
        'color' => '#1DA1F2',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['twitter.com', 'x.com'],
        'category' => 'embeds',
    ],
    'twitter_video' => [
        'type' => 'default',
        'icon' => 'fab fa-x-twitter',
        'color' => '#1DA1F2',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['twitter.com', 'x.com'],
        'category' => 'embeds',
    ],
    'instagram_media' => [
        'type' => 'default',
        'icon' => 'fab fa-instagram',
        'color' => '#F56040',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['www.instagram.com'],
        'category' => 'embeds',
    ],
    'custom_html' => [
        'type' => 'default',
        'icon' => 'fas fa-code',
        'color' => '#02234c',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'max_length' => 16384,
        'category' => 'advanced',
    ],
    'divider' => [
        'type' => 'default',
        'icon' => 'fas fa-grip-lines',
        'color' => '#30a85a',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'category' => 'standard',
    ],
    'list' => [
        'type' => 'default',
        'icon' => 'fas fa-list',
        'color' => '#2b385e',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => 'text',
        'category' => 'standard',
    ],
    'alert' => [
        'type' => 'default',
        'icon' => 'fas fa-bell',
        'color' => '#1500ff',
        'has_statistics' => true,
        'themable' => false,
        'display_dynamic_name' => 'text',
        'category' => 'advanced',
    ],
    'tiktok_profile' => [
        'type' => 'default',
        'icon' => 'fab fa-tiktok',
        'color' => '#FD3E3E',
        'has_statistics' => false,
        'themable' => false,
        'display_dynamic_name' => false,
        'whitelisted_hosts' => ['www.tiktok.com'],
        'category' => 'embeds',
    ],
];

if(settings()->links->google_static_maps_is_enabled) {
    $default_blocks['map'] = [
        'type' => 'default',
        'icon' => 'fas fa-fw fa-map',
        'color' => '#31A952',
        'has_statistics' => true,
        'themable' => false,
        'display_dynamic_name' => 'address',
        'category' => 'advanced',
    ];
}

return array_merge(
    $default_blocks,
    $payment_blocks,
);
